using Content.Shared.Intentions.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Intentions.UI;

[GenerateTypedNameReferences]
/// <summary>
/// Renders one card in the left-side Intentions list.
/// </summary>
public sealed partial class IntentionsListCardControl : Control
{
    private static readonly Color DefaultAccentColor = Color.FromHex("#7A8199FF");
    private static readonly Color CardBorder = Color.FromHex("#343A4D");
    private static readonly Color CardBorderSelected = Color.FromHex("#6D89B5");
    private static readonly Color CardBorderCancelled = Color.FromHex("#454B59");
    private static readonly Color CardBorderCancelledSelected = Color.FromHex("#72819D");
    private static readonly Color CardBackground = Color.FromHex("#202633");
    private static readonly Color CardBackgroundSelected = Color.FromHex("#2A3345");
    private static readonly Color CardBackgroundCancelled = Color.FromHex("#181C24");
    private static readonly Color CardBackgroundCancelledSelected = Color.FromHex("#232A37");
    private static readonly Color TitleColor = Color.FromHex("#EEF1F8");
    private static readonly Color TitleColorCancelled = Color.FromHex("#D8DCE8");
    private static readonly Color SummaryColor = Color.FromHex("#B0B7CB");
    private static readonly Color SummaryColorCancelled = Color.FromHex("#9AA2B8");
    private readonly bool _cancelled;
    private readonly bool _usesHiddenRevealLine;
    private bool _selected;

    /// <summary>
    /// Gets the read-model card currently rendered by this control.
    /// </summary>
    public readonly IntentionsCardView Card;

    /// <summary>
    /// Raised when the card button is pressed.
    /// </summary>
    public event Action<ButtonEventArgs>? OnPressed;

    /// <summary>
    /// Initializes the list-card control from the server-provided read-model.
    /// </summary>
    public IntentionsListCardControl(IntentionsCardView card)
    {
        RobustXamlLoader.Load(this);
        Card = card;
        _cancelled = string.Equals(card.IntentionStatus, "Cancelled", StringComparison.Ordinal);
        _usesHiddenRevealLine = card.IsHidden && string.IsNullOrWhiteSpace(card.CategoryId);

        TitleLabel.SetMessage(IntentionsTextHighlighting.Format(card.Title, card.ResolvedTextParameters));
        ApplySecondaryText(card.Summary);

        IconTexture.HorizontalAlignment = HAlignment.Stretch;
        IconTexture.VerticalAlignment = VAlignment.Stretch;
        IconTexture.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        IconTexture.Visible = card.Icon is not null;
        if (card.Icon is { } icon)
            IconTexture.SetFromSpriteSpecifier(icon);

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.TryFromHex(card.Color) ?? DefaultAccentColor,
        };

        ApplyVisualState();
        MainButton.OnPressed += args => OnPressed?.Invoke(args);
    }

    /// <summary>
    /// Updates the pressed state used to indicate the selected card.
    /// </summary>
    public void SetSelected(bool selected)
    {
        _selected = selected;
        var previousMuteState = MainButton.MuteSounds;
        MainButton.MuteSounds = true;
        try
        {
            MainButton.SetClickPressed(selected);
        }
        finally
        {
            MainButton.MuteSounds = previousMuteState;
        }

        ApplyVisualState();
    }

    /// <summary>
    /// Refreshes the second line for hidden cards while their reveal timer is ticking locally.
    /// </summary>
    public void UpdateHiddenRevealText(TimeSpan currentRoundTime)
    {
        if (!_usesHiddenRevealLine)
            return;

        var revealText = BuildCurrentRevealText(currentRoundTime);
        ApplySecondaryText(revealText);
    }

    /// <summary>
    /// Applies the current expressive card surface and cancelled fade without affecting clickability.
    /// </summary>
    private void ApplyVisualState()
    {
        CardSurface.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ResolveCardBackground(),
            BorderColor = ResolveCardBorder(),
            BorderThickness = new Thickness(1),
        };

        MainButton.Modulate = _cancelled
            ? Color.Gray.WithAlpha(0.7f)
            : Color.White;
        TitleLabel.Modulate = _cancelled
            ? TitleColorCancelled.WithAlpha(0.66f)
            : TitleColor;
        SummaryLabel.Modulate = _cancelled
            ? SummaryColorCancelled.WithAlpha(0.56f)
            : SummaryColor;
        IconTexture.Modulate = _cancelled
            ? Color.White.WithAlpha(0.4f)
            : Color.White;
        AccentBar.Modulate = _cancelled
            ? Color.White.WithAlpha(0.4f)
            : Color.White;
    }

    private Color ResolveCardBackground()
    {
        if (_cancelled)
            return _selected ? CardBackgroundCancelledSelected : CardBackgroundCancelled;

        return _selected ? CardBackgroundSelected : CardBackground;
    }

    private void ApplySecondaryText(string text)
    {
        SummaryLabel.SetMessage(IntentionsTextHighlighting.Format(text, Card.ResolvedTextParameters));
        SummaryLabel.Visible = !string.IsNullOrWhiteSpace(text);
    }

    private string BuildCurrentRevealText(TimeSpan currentRoundTime)
    {
        if (!Card.IsHidden)
            return Card.Summary;

        if (Card.RevealedAtRoundTime is not { } revealTime)
            return Card.RevealText;

        var remaining = revealTime > currentRoundTime ? revealTime - currentRoundTime : TimeSpan.Zero;

        return Loc.GetString(
            "intentions-ui-hidden-reveal-timer",
            ("time", remaining.ToString(@"hh\:mm\:ss")));
    }

    private Color ResolveCardBorder()
    {
        if (_cancelled)
            return _selected ? CardBorderCancelledSelected : CardBorderCancelled;

        return _selected ? CardBorderSelected : CardBorder;
    }
}
