using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Robust.Shared.GameObjects;

namespace Content.Shared.Intentions.Runtime;

/// <summary>
/// Round-scoped runtime identifier for a committed scenario instance.
/// </summary>
public readonly record struct ScenarioInstanceUid(long Value)
{
    /// <summary>
    /// Returns the numeric identifier as a string for logs and debug output.
    /// </summary>
    public override string ToString()
    {
        return Value.ToString();
    }
}

/// <summary>
/// Round-scoped runtime identifier for a committed intention instance.
/// </summary>
public readonly record struct IntentionInstanceUid(long Value)
{
    /// <summary>
    /// Returns the numeric identifier as a string for logs and debug output.
    /// </summary>
    public override string ToString()
    {
        return Value.ToString();
    }
}

/// <summary>
/// Runtime scenario state committed by the atomic Intentions commit step.
/// </summary>
public sealed class ScenarioInstance
{
    /// <summary>
    /// Creates one committed scenario instance.
    /// </summary>
    public ScenarioInstance(
        ScenarioInstanceUid uid,
        string scenarioTemplateId,
        string categoryId,
        ScenarioRuntimeStatus status,
        string ownerSlotId,
        EntityUid ownerMindId,
        EntityUid ownerEntityUid,
        int waveId,
        TimeSpan createdAtRoundTime,
        IEnumerable<ScenarioSlotAssignment> slotAssignments,
        TimeSpan? statusChangedAtRoundTime = null,
        string? statusReason = null)
    {
        Uid = uid;
        ScenarioTemplateId = scenarioTemplateId;
        CategoryId = categoryId;
        Status = status;
        OwnerSlotId = ownerSlotId;
        OwnerMindId = ownerMindId;
        OwnerEntityUid = ownerEntityUid;
        WaveId = waveId;
        CreatedAtRoundTime = createdAtRoundTime;
        SlotAssignments = slotAssignments.ToImmutableArray();
        StatusChangedAtRoundTime = statusChangedAtRoundTime ?? createdAtRoundTime;
        StatusReason = statusReason;
    }

    /// <summary>
    /// Runtime uid generated by the registry for this scenario.
    /// </summary>
    public ScenarioInstanceUid Uid { get; }

    /// <summary>
    /// Source scenario template id used to build this runtime scenario.
    /// </summary>
    public string ScenarioTemplateId { get; }

    /// <summary>
    /// Category id copied from the source scenario template.
    /// </summary>
    public string CategoryId { get; }

    /// <summary>
    /// Current runtime lifecycle status of the scenario.
    /// </summary>
    public ScenarioRuntimeStatus Status { get; }

    /// <summary>
    /// Slot id designated as the owner of the scenario.
    /// </summary>
    public string OwnerSlotId { get; }

    /// <summary>
    /// Mind that currently owns the primary scenario slot.
    /// </summary>
    public EntityUid OwnerMindId { get; }

    /// <summary>
    /// Current body entity for the scenario owner.
    /// </summary>
    public EntityUid OwnerEntityUid { get; }

    /// <summary>
    /// Wave id that committed this scenario.
    /// </summary>
    public int WaveId { get; }

    /// <summary>
    /// Round time when this scenario instance was created.
    /// </summary>
    public TimeSpan CreatedAtRoundTime { get; }

    /// <summary>
    /// Round time when the scenario status last changed.
    /// </summary>
    public TimeSpan StatusChangedAtRoundTime { get; }

    /// <summary>
    /// Optional reason describing the latest lifecycle transition.
    /// </summary>
    public string? StatusReason { get; }

    /// <summary>
    /// Immutable slot assignment list for this scenario.
    /// </summary>
    public ImmutableArray<ScenarioSlotAssignment> SlotAssignments { get; }

    /// <summary>
    /// Returns a copy with a new lifecycle status.
    /// </summary>
    public ScenarioInstance WithStatus(ScenarioRuntimeStatus status, TimeSpan now, string? reason)
    {
        return Copy(status: status, statusChangedAtRoundTime: now, statusReason: reason);
    }

    /// <summary>
    /// Returns a copy with an updated owner body entity.
    /// </summary>
    public ScenarioInstance WithOwnerEntity(EntityUid ownerEntityUid, TimeSpan now, string? reason)
    {
        return Copy(ownerEntityUid: ownerEntityUid, statusChangedAtRoundTime: now, statusReason: reason);
    }

    /// <summary>
    /// Returns a copy with one slot assignment replaced.
    /// </summary>
    public ScenarioInstance WithSlotAssignment(ScenarioSlotAssignment assignment)
    {
        var assignments = SlotAssignments
            .Select(existing => existing.SlotId == assignment.SlotId ? assignment : existing)
            .ToImmutableArray();

        return Copy(slotAssignments: assignments);
    }

    /// <summary>
    /// Returns a copy with a fully replaced slot assignment list.
    /// </summary>
    public ScenarioInstance WithSlotAssignments(IEnumerable<ScenarioSlotAssignment> assignments)
    {
        return Copy(slotAssignments: assignments);
    }

    /// <summary>
    /// Internal copy helper used by lifecycle and commit operations.
    /// </summary>
    private ScenarioInstance Copy(
        ScenarioRuntimeStatus? status = null,
        EntityUid? ownerEntityUid = null,
        IEnumerable<ScenarioSlotAssignment>? slotAssignments = null,
        TimeSpan? statusChangedAtRoundTime = null,
        string? statusReason = null)
    {
        return new ScenarioInstance(
            Uid,
            ScenarioTemplateId,
            CategoryId,
            status ?? Status,
            OwnerSlotId,
            OwnerMindId,
            ownerEntityUid ?? OwnerEntityUid,
            WaveId,
            CreatedAtRoundTime,
            slotAssignments ?? SlotAssignments,
            statusChangedAtRoundTime ?? StatusChangedAtRoundTime,
            statusReason ?? StatusReason);
    }
}

/// <summary>
/// Runtime assignment for one scenario slot and its committed intention instance.
/// </summary>
public sealed class ScenarioSlotAssignment
{
    /// <summary>
    /// Creates a runtime slot assignment.
    /// </summary>
    public ScenarioSlotAssignment(
        ScenarioInstanceUid scenarioUid,
        string slotId,
        string kind,
        EntityUid mindId,
        EntityUid ownerEntityUid,
        ScenarioSlotAssignmentStatus status,
        IntentionInstanceUid intentionUid,
        bool required,
        bool wasBound,
        string? boundToSlotId,
        TimeSpan assignedAtRoundTime,
        TimeSpan? statusChangedAtRoundTime = null,
        string? statusReason = null)
    {
        ScenarioUid = scenarioUid;
        SlotId = slotId;
        Kind = kind;
        MindId = mindId;
        OwnerEntityUid = ownerEntityUid;
        Status = status;
        IntentionUid = intentionUid;
        Required = required;
        WasBound = wasBound;
        BoundToSlotId = boundToSlotId;
        AssignedAtRoundTime = assignedAtRoundTime;
        StatusChangedAtRoundTime = statusChangedAtRoundTime ?? assignedAtRoundTime;
        StatusReason = statusReason;
    }

    /// <summary>
    /// Owning runtime scenario.
    /// </summary>
    public ScenarioInstanceUid ScenarioUid { get; }

    /// <summary>
    /// Slot id copied from the scenario template.
    /// </summary>
    public string SlotId { get; }

    /// <summary>
    /// Slot kind copied from the scenario entry.
    /// </summary>
    public string Kind { get; }

    /// <summary>
    /// Mind selected for this slot.
    /// </summary>
    public EntityUid MindId { get; }

    /// <summary>
    /// Current body entity for the selected mind.
    /// </summary>
    public EntityUid OwnerEntityUid { get; }

    /// <summary>
    /// Current runtime status of the slot assignment.
    /// </summary>
    public ScenarioSlotAssignmentStatus Status { get; }

    /// <summary>
    /// Intention instance created for this slot.
    /// </summary>
    public IntentionInstanceUid IntentionUid { get; }

    /// <summary>
    /// Whether this slot was required by the scenario template.
    /// </summary>
    public bool Required { get; }

    /// <summary>
    /// Whether the slot reused another already-selected candidate.
    /// </summary>
    public bool WasBound { get; }

    /// <summary>
    /// Referenced slot id when the assignment was copied from another slot.
    /// </summary>
    public string? BoundToSlotId { get; }

    /// <summary>
    /// Round time when the slot was first assigned.
    /// </summary>
    public TimeSpan AssignedAtRoundTime { get; }

    /// <summary>
    /// Round time when the slot status last changed.
    /// </summary>
    public TimeSpan StatusChangedAtRoundTime { get; }

    /// <summary>
    /// Optional reason describing the latest lifecycle transition.
    /// </summary>
    public string? StatusReason { get; }

    /// <summary>
    /// Returns a copy with a new slot status.
    /// </summary>
    public ScenarioSlotAssignment WithStatus(ScenarioSlotAssignmentStatus status, TimeSpan now, string? reason)
    {
        return Copy(status: status, statusChangedAtRoundTime: now, statusReason: reason);
    }

    /// <summary>
    /// Returns a copy with an updated owner body entity.
    /// </summary>
    public ScenarioSlotAssignment WithOwnerEntity(EntityUid ownerEntityUid, TimeSpan now, string? reason)
    {
        return Copy(ownerEntityUid: ownerEntityUid, statusChangedAtRoundTime: now, statusReason: reason);
    }

    /// <summary>
    /// Returns a copy that updates both slot status and owner body entity.
    /// </summary>
    public ScenarioSlotAssignment WithStatusAndOwnerEntity(
        ScenarioSlotAssignmentStatus status,
        EntityUid ownerEntityUid,
        TimeSpan now,
        string? reason)
    {
        return Copy(status: status, ownerEntityUid: ownerEntityUid, statusChangedAtRoundTime: now, statusReason: reason);
    }

    /// <summary>
    /// Internal copy helper used by lifecycle transitions.
    /// </summary>
    private ScenarioSlotAssignment Copy(
        ScenarioSlotAssignmentStatus? status = null,
        EntityUid? ownerEntityUid = null,
        TimeSpan? statusChangedAtRoundTime = null,
        string? statusReason = null)
    {
        return new ScenarioSlotAssignment(
            ScenarioUid,
            SlotId,
            Kind,
            MindId,
            ownerEntityUid ?? OwnerEntityUid,
            status ?? Status,
            IntentionUid,
            Required,
            WasBound,
            BoundToSlotId,
            AssignedAtRoundTime,
            statusChangedAtRoundTime ?? StatusChangedAtRoundTime,
            statusReason ?? StatusReason);
    }
}

/// <summary>
/// Runtime intention instance committed for one scenario slot.
/// </summary>
public sealed class IntentionInstance
{
    /// <summary>
    /// Creates a runtime intention instance.
    /// </summary>
    public IntentionInstance(
        IntentionInstanceUid uid,
        string intentionTemplateId,
        ScenarioInstanceUid scenarioUid,
        string slotId,
        EntityUid ownerMindId,
        EntityUid ownerEntityUid,
        string kind,
        IntentionRuntimeStatus status,
        TimeSpan assignedAtRoundTime,
        TimeSpan statusChangedAtRoundTime,
        bool isHidden,
        IntentionRevealMode revealMode,
        TimeSpan? revealedAtRoundTime,
        IReadOnlyDictionary<string, string> resolvedTextParameters,
        string? copyableTextResolved,
        string? failureReason = null)
    {
        Uid = uid;
        IntentionTemplateId = intentionTemplateId;
        ScenarioUid = scenarioUid;
        SlotId = slotId;
        OwnerMindId = ownerMindId;
        OwnerEntityUid = ownerEntityUid;
        Kind = kind;
        Status = status;
        AssignedAtRoundTime = assignedAtRoundTime;
        StatusChangedAtRoundTime = statusChangedAtRoundTime;
        IsHidden = isHidden;
        RevealMode = revealMode;
        RevealedAtRoundTime = revealedAtRoundTime;
        ResolvedTextParameters = resolvedTextParameters.ToImmutableDictionary(StringComparer.Ordinal);
        CopyableTextResolved = copyableTextResolved;
        FailureReason = failureReason;
    }

    /// <summary>
    /// Runtime uid generated by the registry for this intention.
    /// </summary>
    public IntentionInstanceUid Uid { get; }

    /// <summary>
    /// Source intention template id used to create this runtime instance.
    /// </summary>
    public string IntentionTemplateId { get; }

    /// <summary>
    /// Runtime scenario that owns this intention instance.
    /// </summary>
    public ScenarioInstanceUid ScenarioUid { get; }

    /// <summary>
    /// Slot id that produced this intention instance.
    /// </summary>
    public string SlotId { get; }

    /// <summary>
    /// Mind that currently owns the intention.
    /// </summary>
    public EntityUid OwnerMindId { get; }

    /// <summary>
    /// Current body entity for the intention owner.
    /// </summary>
    public EntityUid OwnerEntityUid { get; }

    /// <summary>
    /// Primary or secondary kind copied from the scenario slot.
    /// </summary>
    public string Kind { get; }

    /// <summary>
    /// Current runtime status of the intention instance.
    /// </summary>
    public IntentionRuntimeStatus Status { get; }

    /// <summary>
    /// Round time when the intention was assigned.
    /// </summary>
    public TimeSpan AssignedAtRoundTime { get; }

    /// <summary>
    /// Round time when the intention status last changed.
    /// </summary>
    public TimeSpan StatusChangedAtRoundTime { get; }

    /// <summary>
    /// Whether the intention is currently hidden from the player view.
    /// </summary>
    public bool IsHidden { get; }

    /// <summary>
    /// Reveal mode captured at commit time.
    /// </summary>
    public IntentionRevealMode RevealMode { get; }

    /// <summary>
    /// Scheduled reveal time for timer-based hidden intentions, if any.
    /// </summary>
    public TimeSpan? RevealedAtRoundTime { get; }

    /// <summary>
    /// Resolved text parameters captured once at commit time.
    /// </summary>
    public ImmutableDictionary<string, string> ResolvedTextParameters { get; }

    /// <summary>
    /// Ready-to-copy material text rendered once at commit time.
    /// </summary>
    public string? CopyableTextResolved { get; }

    /// <summary>
    /// Optional runtime failure or lifecycle reason.
    /// </summary>
    public string? FailureReason { get; }

    /// <summary>
    /// Returns a copy with a new intention status.
    /// </summary>
    public IntentionInstance WithStatus(IntentionRuntimeStatus status, TimeSpan now, string? reason)
    {
        return Copy(status: status, statusChangedAtRoundTime: now, failureReason: reason);
    }

    /// <summary>
    /// Returns a copy with an updated owner body entity.
    /// </summary>
    public IntentionInstance WithOwnerEntity(EntityUid ownerEntityUid, TimeSpan now, string? reason)
    {
        return Copy(ownerEntityUid: ownerEntityUid, statusChangedAtRoundTime: now, failureReason: reason);
    }

    /// <summary>
    /// Returns a copy marked as revealed while preserving resolved text.
    /// </summary>
    public IntentionInstance WithRevealed()
    {
        return Copy(isHidden: false);
    }

    /// <summary>
    /// Internal copy helper used by reveal and lifecycle transitions.
    /// </summary>
    private IntentionInstance Copy(
        IntentionRuntimeStatus? status = null,
        EntityUid? ownerEntityUid = null,
        TimeSpan? statusChangedAtRoundTime = null,
        bool? isHidden = null,
        string? failureReason = null)
    {
        return new IntentionInstance(
            Uid,
            IntentionTemplateId,
            ScenarioUid,
            SlotId,
            OwnerMindId,
            ownerEntityUid ?? OwnerEntityUid,
            Kind,
            status ?? Status,
            AssignedAtRoundTime,
            statusChangedAtRoundTime ?? StatusChangedAtRoundTime,
            isHidden ?? IsHidden,
            RevealMode,
            RevealedAtRoundTime,
            ResolvedTextParameters,
            CopyableTextResolved,
            failureReason ?? FailureReason);
    }
}

/// <summary>
/// Runtime lifecycle states for committed scenarios.
/// </summary>
public enum ScenarioRuntimeStatus : byte
{
    Active,
    Frozen,
    Cancelled,
}

/// <summary>
/// Runtime lifecycle states for committed intention instances.
/// </summary>
public enum IntentionRuntimeStatus : byte
{
    Active,
    Cancelled,
}

/// <summary>
/// Runtime lifecycle states for committed slot assignments.
/// </summary>
public enum ScenarioSlotAssignmentStatus : byte
{
    Assigned,
    Missing,
    Invalidated,
}

/// <summary>
/// Runtime reveal modes supported by the MVP implementation.
/// </summary>
public enum IntentionRevealMode : byte
{
    None,
    Timer,
}

/// <summary>
/// Result of attempting to atomically commit one built scenario into the runtime registry.
/// </summary>
public sealed class CommitScenarioBuildResult
{
    /// <summary>
    /// Creates a commit result.
    /// </summary>
    private CommitScenarioBuildResult(
        bool isSuccess,
        ScenarioInstance? scenarioInstance,
        IEnumerable<IntentionInstance> intentionInstances,
        string? failureReason,
        bool rollbackCompleted)
    {
        IsSuccess = isSuccess;
        ScenarioInstance = scenarioInstance;
        IntentionInstances = intentionInstances.ToImmutableArray();
        FailureReason = failureReason;
        RollbackCompleted = rollbackCompleted;
    }

    /// <summary>
    /// Whether the commit completed successfully.
    /// </summary>
    public bool IsSuccess { get; }

    /// <summary>
    /// Committed scenario instance when the commit succeeded.
    /// </summary>
    public ScenarioInstance? ScenarioInstance { get; }

    /// <summary>
    /// Intention instances created by the successful commit.
    /// </summary>
    public ImmutableArray<IntentionInstance> IntentionInstances { get; }

    /// <summary>
    /// Failure reason when the commit could not complete.
    /// </summary>
    public string? FailureReason { get; }

    /// <summary>
    /// Whether rollback finished successfully after a failed commit attempt.
    /// </summary>
    public bool RollbackCompleted { get; }

    /// <summary>
    /// Creates a successful commit result.
    /// </summary>
    public static CommitScenarioBuildResult Success(ScenarioInstance scenarioInstance, IEnumerable<IntentionInstance> intentionInstances)
    {
        return new CommitScenarioBuildResult(true, scenarioInstance, intentionInstances, null, rollbackCompleted: true);
    }

    /// <summary>
    /// Creates a failed commit result.
    /// </summary>
    public static CommitScenarioBuildResult Failure(string failureReason, bool rollbackCompleted)
    {
        return new CommitScenarioBuildResult(false, null, Array.Empty<IntentionInstance>(), failureReason, rollbackCompleted);
    }
}
